"""add all new columns

Revision ID: e87c8be47b88
Revises: 79d4ca642368
Create Date: 2026-04-25 19:32:52.693881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87c8be47b88'
down_revision = '79d4ca642368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty', sa.Float(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=300), nullable=True))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_window_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shuffle_questions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negative_marking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negative_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('is_public')
        batch_op.drop_column('negative_penalty')
        batch_op.drop_column('negative_marking')
        batch_op.drop_column('shuffle_questions')
        batch_op.drop_column('join_window_minutes')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_column('penalty')

    # ### end Alembic commands ###
